# Generated by Django 5.0.2 on 2024-02-25 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landbids", "0001_initial"),
        ("listings", "0013_alter_parcel_parcel_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="bid_price",
        ),
        migrations.RemoveField(
            model_name="bid",
            name="fraction",
        ),
        migrations.RemoveField(
            model_name="bid",
            name="size",
        ),
        migrations.RemoveField(
            model_name="bid",
            name="whole_number",
        ),
        migrations.AddField(
            model_name="bid",
            name="land_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="IMAGES_of_bids_on_parcel",
                to="listings.landlistingimages",
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="land_map",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="map_of_bids_on_parcel",
                to="listings.landlistingmaps",
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="parcel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids_on_parcel",
                to="listings.parcel",
            ),
        ),
    ]
