# Generated by Django 5.0.2 on 2024-02-25 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("landbids", "0003_alter_bid_bidder_alter_bid_listing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="land_image",
        ),
        migrations.RemoveField(
            model_name="bid",
            name="land_map",
        ),
    ]
