# Generated by Django 5.0.2 on 2024-03-23 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("surveyors", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="surveyorprofile",
            old_name="fullname",
            new_name="fullName",
        ),
    ]
