# Generated by Django 5.0.3 on 2024-03-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveyors", "0002_rename_fullname_surveyorprofile_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyorprofile",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="surveyorprofile",
            name="rates",
            field=models.FloatField(default=0),
        ),
    ]
