# Generated by Django 5.0.2 on 2024-03-23 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lawyers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lawyerprofile",
            old_name="fullname",
            new_name="fullName",
        ),
    ]
