# Generated by Django 5.0.3 on 2024-03-26 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_notification_is_read_notification_sender_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="is_read",
        ),
    ]
