# Generated by Django 5.0.3 on 2024-03-26 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0020_landlisting_description"),
        ("notifications", "0004_notification_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="land_listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="listings.landlisting",
            ),
        ),
    ]
