# Generated by Django 4.2.4 on 2023-09-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlisting",
            name="telephone_number",
            field=models.CharField(default=2232113414, max_length=20),
            preserve_default=False,
        ),
    ]
