# Generated by Django 4.2.4 on 2023-10-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_landlisting_telephone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlisting",
            name="size",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total land amount in acres",
                max_digits=10,
            ),
            preserve_default=False,
        ),
    ]
