# Generated by Django 4.2.7 on 2023-12-05 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0003_landlisting_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlisting",
            name="active_bid_size",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="LandListingImages_Maps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "land_images",
                    models.ImageField(blank=True, null=True, upload_to="land_images"),
                ),
                (
                    "land_map",
                    models.ImageField(blank=True, null=True, upload_to="land_maps"),
                ),
                (
                    "land_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="listings.landlisting",
                    ),
                ),
            ],
        ),
    ]
