# Generated by Django 5.0.2 on 2024-02-25 01:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0008_remove_landparcel_land_listing_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parcel",
            name="parcel_id",
        ),
        migrations.AddField(
            model_name="parcel",
            name="parcel_label",
            field=models.IntegerField(
                default=django.utils.timezone.now, max_length=100, unique=True
            ),
            preserve_default=False,
        ),
    ]
