# Generated by Django 5.0.2 on 2024-02-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0011_remove_parcel_parcel_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="parcel_label",
            field=models.IntegerField(default=4, unique=True),
            preserve_default=False,
        ),
    ]
