# Generated by Django 5.0.2 on 2024-02-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0013_alter_parcel_parcel_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcel",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("pending", "Pending"),
                    ("sold", "Sold"),
                ],
                default="available",
                max_length=50,
            ),
        ),
    ]
