# Generated by Django 5.0.2 on 2024-02-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0014_alter_parcel_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlisting",
            name="listing_type",
            field=models.CharField(
                choices=[("sale", "For Sale"), ("lease", "For Lease")],
                default="sale",
                max_length=5,
                null=True,
            ),
        ),
    ]
