# Generated by Django 5.0.2 on 2024-03-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0018_sellerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="fullName",
            field=models.CharField(default="seller", max_length=255),
            preserve_default=False,
        ),
    ]
