# Generated by Django 5.0.3 on 2024-03-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0019_sellerprofile_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlisting",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
