# Generated by Django 5.0.3 on 2024-03-28 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0020_landlisting_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parcel",
            name="parcel_label",
        ),
    ]
