# Generated by Django 5.0.3 on 2024-03-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0021_remove_parcel_parcel_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="parcel_label",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
