# Generated by Django 5.0.3 on 2024-03-28 22:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0024_parcel_parcel_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parcel",
            name="parcel_id",
        ),
    ]
