# Generated by Django 5.0.3 on 2024-03-29 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0025_remove_parcel_parcel_id"),
        ("surveyors", "0002_rename_fullname_surveyorprofile_fullname"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_deed_number", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "surveyor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to="surveyors.surveyorprofile",
                    ),
                ),
            ],
        ),
    ]
