# Generated by Django 5.0.3 on 2024-03-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0026_sellerinquiry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellerprofile",
            name="landRegistrationNumber",
        ),
        migrations.RemoveField(
            model_name="sellerprofile",
            name="landTitleDeedNumber",
        ),
        migrations.AddField(
            model_name="landlisting",
            name="landTitleDeedNumber",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
