# Generated by Django 5.0.3 on 2024-03-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0028_sellerinquiry_phonenumber_sellerinquiry_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerinquiry",
            name="full_name",
            field=models.CharField(default="richie", max_length=255),
            preserve_default=False,
        ),
    ]
