# Generated by Django 5.0.3 on 2024-03-29 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0029_sellerinquiry_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlisting",
            name="seller_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="listings.sellerprofile",
            ),
        ),
    ]
