# Generated by Django 5.0.2 on 2024-03-22 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_customuser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="user_type",
        ),
    ]
