# Generated by Django 5.0.3 on 2024-03-27 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("landbids", "0005_buyerprofile"),
        ("lawyers", "0002_rename_fullname_lawyerprofile_fullname"),
        ("listings", "0020_landlisting_description"),
        ("surveyors", "0002_rename_fullname_surveyorprofile_fullname"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction",
                        to="landbids.bid",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        limit_choices_to={"role": "buyer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="buyer_transactions",
                        to="landbids.buyerprofile",
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lawyer_transactions",
                        to="lawyers.lawyerprofile",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        limit_choices_to={"role": "seller"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seller_transactions",
                        to="listings.sellerprofile",
                    ),
                ),
                (
                    "surveyor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surveyor_transactions",
                        to="surveyors.surveyorprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
