# Generated by Django 5.0.3 on 2024-03-29 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landbids", "0005_buyerprofile"),
        ("listings", "0025_remove_parcel_parcel_id"),
        ("transactions", "0002_remove_transaction_user_transaction_listing_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="bid",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction",
                to="landbids.bid",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="buyer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="listing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="listings.landlisting",
            ),
        ),
    ]
