# Generated by Django 5.0.3 on 2024-03-29 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landbids", "0005_buyerprofile"),
        ("listings", "0029_sellerinquiry_full_name"),
        ("transactions", "0003_alter_transaction_bid_alter_transaction_buyer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="buyer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_transactions",
                to="landbids.buyerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="seller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller_transactions",
                to="listings.sellerprofile",
            ),
        ),
    ]
